# Setup

In [1]:
!python --version

Python 3.12.12


In [2]:
!git clone https://github.com/jiteshmr-2025/wix-1007.git

Cloning into 'wix-1007'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (4/4), 6.63 KiB | 3.32 MiB/s, done.


In [7]:
!cd wix-1007/

/bin/bash: line 1: cd: wix-1007/: No such file or directory


# Tutorial 3
## Question 1

In [9]:
import numpy as np

In [11]:
arr = np.array([[1, 1], [2, 3]])
print(arr)

[[1 1]
 [2 3]]


## Question 2

In [12]:
arr = np.array(np.random.randint(low = 0, high = 100, size = (3,4)))

In [13]:
print(arr)

[[51 64 59  7]
 [92  0 70 10]
 [14  4 80 27]]


## Question 3

In [14]:
arr_2 =  np.zeros((2, 2))

In [15]:
arr_2

array([[0., 0.],
       [0., 0.]])

In [18]:
arr_3 = np.ones((3, 2))

In [19]:
arr_3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Question 4

In [22]:
arr_4 = np.array(np.random.randint(low = 0, high = 100, size = (6, 3)))
arr_4

array([[71,  9, 67],
       [80, 49, 70],
       [39, 19, 68],
       [65, 17,  4],
       [45, 55, 14],
       [56, 36, 37]])

In [23]:
arr_4.transpose()

array([[71, 80, 39, 65, 45, 56],
       [ 9, 49, 19, 17, 55, 36],
       [67, 70, 68,  4, 14, 37]])

## Question 5

In [27]:
# Generate two random np array
arr_rand1 = np.array(np.random.randint(low = 0, high = 100, size = (6, 3)))
arr_rand2 = np.array(np.random.randint(low = 0, high = 100, size = (3, 7)))

In [30]:
arr_final = np.dot(arr_rand1, arr_rand2)
arr_final

array([[ 5842,  2730,  5692,  3430,  1696,  5084,  6812],
       [ 8051,  2837,  9907,  9255,  8451,  6031,  5573],
       [ 4098,  2002,  4184,  2850,  1382,  3600,  4820],
       [ 9612,  2640,  8862,  4248,  5802,  7110,  7386],
       [ 9618,  3806, 11346, 10010,  8218,  7578,  8014],
       [ 8296,  1906,  8219,  4902,  6951,  5783,  5053]])

## Github Integration